name:                core1
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/DylanSp/core1#readme
license:             MIT
author:              Dylan
maintainer:          dylan.richard.sprague@gmail.com
copyright:           value
category:            value
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers

library:
  source-dirs:        src

executables:
  core1-exe:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - core1

tests:
  core1-test:
    source-dirs:      test
    main:             Test.hs
    dependencies:
      - core1
      - hedgehog
      - tasty
      - tasty-hedgehog
      - tasty-hunit